MILVUS_PATH : "/mnt/d/UpstageNLP_test/rag_upstage/MILVUS" # path to MILVUS database
TEST_PATH: "/mnt/d/UpstageNLP_milvus/rag_upstage/test_data/test_samples(ewha).csv" # path for test file
DATA_PATH: "/mnt/d/UpstageNLP_milvus/rag_upstage/data" # path for pdf files

# template for prompt without wikipedia search
PROMPT_TEMPLATE: |
  Now, answer the following question based on the provided context.
  Let's think step by step to find the most accurate answer.
  If the answer is not present in the context, write 'The information is not present in the context.'
  ---
  Q: {question}
  ---
  Context: {context}

# template for prompt with wikipedia search
PROMPT_TEMPLATE_WIKI: |
  Now, answer the following question based on the provided context.
  Let's think step by step to find the most accurate answer.
  ---
  Q: {question}
  ---
  Context: {context}
  